require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - spec/support/broken_code.rb

# --------------------- Security ----------------------
Security/Eval:
  Exclude:
    - lib/senior/agent.rb

# ----------------------- Style -----------------------

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

# ----------------------- Layout ----------------------

Layout/LineLength:
  Max: 120

# ---------------------- Metrics ----------------------

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - senior.gemspec

Metrics/MethodLength:
  Exclude:
    - lib/senior/brains/open_ai.rb

# ----------------------- RSpec -----------------------

RSpec/ExampleLength:
  Enabled: false
