# frozen_string_literal: true

module Senior
  module Commands
    class AutoDebugMethod
      def initialize: (?_IBrain brain) -> void
      def call: (Method broken_method, untyped args, String? | nil broken_method_source) -> untyped

      private

      attr_reader brain: _IBrain
    end
  end
end
