module Senior
  VERSION: String

  self.@configuration: Configuration::Main
  self.@brain: _IBrain

  def self.auto_debug_method: (Method broken_method, untyped args, String? | nil broken_method_source) -> untyped
  def self.suggest_method_fix: (Method broken_method, untyped args) -> String
  def self.configuration: -> Configuration::Main
  def self.configure: -> untyped
  def self.brain: -> _IBrain
end
