module Senior
  VERSION: String
  self.@agent: Agent

  def self.auto_debug: (Method broken_method, untyped args, String? | nil broken_method_source) -> untyped

  def self.suggest_fix: (Method broken_method, untyped args) -> String

  private

  def self.agent: -> Agent
end
